- name: AWS | Disable termination protection
  community.aws.ec2_instance:
    name: "{{ botinstance_name }}"
    termination_protection: no
    region: "{{ botinstance_region }}"
  tags:
    - botinstance

- name: AWS | Destroy instance
  community.aws.ec2_instance:
    name: "{{ botinstance_name }}"
    region: "{{ botinstance_region }}"
    state: absent
  tags:
    - botinstance

- name: AWS | Get Route 53 records
  community.aws.route53:
    state: get
    zone: "{{ botinstance_dns_zone }}"
    record: "{{ item.record }}"
    type: "{{ item.type }}"
  loop: "{{ botinstance_dns_entries }}"
  register: current_dns_records
  tags:
    - botinstance

- name: AWS | Delete route 53 entries
  community.aws.route53:
    state: absent
    zone: "{{ botinstance_dns_zone }}"
    record: "{{ item.set.record }}"
    ttl: "{{ item.set.ttl | default('300') }}"
    type: "{{ item.set.type }}"
    value: "{{ item.set.value | default(omit) }}"
  when: item.set | length > 0
  loop: "{{ current_dns_records.results }}"
  tags:
    - botinstance
