dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint -x 204,403,502
  yamllint -c molecule/default/yamllint.yml .
platforms:
  - name: ansibullbot_instance-test-${MOLECULE_DISTRIBUTION:-centos7}
    image: "quay.io/samdoran/${MOLECULE_DISTRIBUTION:-centos7}-ansible"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: debug
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    # - converge
    # - idempotence
    - destroy
verifier:
  name: ansible
